# Makefile — KWS Spike Validation
#
# This Makefile builds and runs RISC-V Spike benchmarks for each KWS model.
# Each model consists of two files:
#
#   <model_name>_weights.h   — NNoM int8 weights (C header, generated by NNoM)
#   <model_name>_main.c      — Minimal inference harness (reads test_data.bin)
#
# BUILD
# -----
#   make                                # build all models
#   make build_strided_s16_nodil        # build one model
#
# RUN ON SPIKE
# ------------
#   make run_strided_s16_nodil          # run accuracy benchmark
#
# GENERATE TEST DATA
# ------------------
#   make test_data                      # generate test_data.bin from GSCD
#
# ADDING A NEW MODEL
# ------------------
#   1. Place <model_name>_weights.h in this directory
#   2. Place <model_name>_main.c in this directory
#   3. Add a build target below (copy the strided_s16_nodil target as template)
#   4. Add the new target to the $(ALL_TARGETS) list
#
# PREREQUISITES
# -------------
#   make setup    — check that all tools are found

# ── Toolchain ─────────────────────────────────────────────────────────────────

CC    = /opt/riscv/gcc15/bin/riscv32-unknown-elf-gcc
SPIKE = /opt/riscv/bin/spike
PK    = /opt/riscv/riscv32-unknown-elf/bin/pk

# RV32IMC with Zicsr + Zifencei extensions.
# ilp32: 32-bit pointers, no hardware FPU.
ARCH  = rv32imc_zicsr_zifencei
ABI   = ilp32

# ── NNoM ──────────────────────────────────────────────────────────────────────

NNOM_DIR  = nnom
NNOM_SRCS = $(wildcard $(NNOM_DIR)/src/core/*.c) \
            $(wildcard $(NNOM_DIR)/src/layers/*.c) \
            $(wildcard $(NNOM_DIR)/src/backends/*.c)
NNOM_INC  = -I$(NNOM_DIR)/inc -I$(NNOM_DIR)/port

# ── Compiler flags ────────────────────────────────────────────────────────────

CFLAGS = -march=$(ARCH) -mabi=$(ABI) \
         -O2 -std=c99 \
         -DNNOM_USING_STATIC_MEMORY \
         $(NNOM_INC) \
         -I.

LDFLAGS = -lm

# ── Spike flags ───────────────────────────────────────────────────────────────

# -m256: 256 MB of guest memory.
# NNoM static buffer = 1 MB; test file (full GSCD test split) = ~35 MB.
# 256 MB is more than enough.
SPIKE_FLAGS = --isa=$(ARCH) -m256

# ── Build directory ───────────────────────────────────────────────────────────

BUILD = build

# ── All models ────────────────────────────────────────────────────────────────
# Add new model ELF names here when you add a new model.

ALL_TARGETS = $(BUILD)/strided_s16_nodil

# ── Default target ────────────────────────────────────────────────────────────

.PHONY: all clean test_data setup help
all: $(ALL_TARGETS)
	@echo ""
	@echo "All models built.  Run: make run_strided_s16_nodil"

# ── strided_s16_nodil ─────────────────────────────────────────────────────────
#
# Model:    nnom-qat-strided-s16-nodil
# Accuracy: 85.3% NNoM int8 (validated on Spike)
# MACs:     ~5.46M per inference
# Weights:  strided_s16_nodil_weights.h

$(BUILD)/strided_s16_nodil: strided_s16_nodil_main.c \
                             strided_s16_nodil_weights.h \
                             $(NNOM_SRCS)
	@mkdir -p $(BUILD)
	@echo "Compiling strided_s16_nodil ..."
	$(CC) $(CFLAGS) \
	    strided_s16_nodil_main.c \
	    $(NNOM_SRCS) \
	    -o $@ $(LDFLAGS)
	@echo "Built: $@"

.PHONY: build_strided_s16_nodil run_strided_s16_nodil

build_strided_s16_nodil: $(BUILD)/strided_s16_nodil

run_strided_s16_nodil: $(BUILD)/strided_s16_nodil test_data.bin
	@echo ""
	@echo "Running strided_s16_nodil on Spike ..."
	@echo "Expected accuracy: ~85.3%"
	@echo ""
	cd $(BUILD) && $(SPIKE) $(SPIKE_FLAGS) $(PK) strided_s16_nodil \
	    | tee strided_s16_nodil.log
	@echo ""
	@grep "ACCURACY:" $(BUILD)/strided_s16_nodil.log || true
	@echo "Full log: $(BUILD)/strided_s16_nodil.log"

# ── Template for adding a new model ──────────────────────────────────────────
# To add a new model (e.g. da4a), uncomment and edit:
#
# $(BUILD)/da4a: da4a_main.c da4a_weights.h $(NNOM_SRCS)
# 	@mkdir -p $(BUILD)
# 	$(CC) $(CFLAGS) da4a_main.c $(NNOM_SRCS) -o $@ $(LDFLAGS)
#
# .PHONY: build_da4a run_da4a
# build_da4a: $(BUILD)/da4a
#
# run_da4a: $(BUILD)/da4a test_data.bin
# 	cd $(BUILD) && $(SPIKE) $(SPIKE_FLAGS) $(PK) da4a | tee da4a.log
#
# Also add $(BUILD)/da4a to ALL_TARGETS above.

# ── Test data ─────────────────────────────────────────────────────────────────

test_data: test_data.bin

test_data.bin:
	@echo "Generating test_data.bin ..."
	python3 generate_test_data.py --output test_data.bin
	@cp test_data.bin $(BUILD)/test_data.bin 2>/dev/null || true

# Copy test_data.bin into build/ when running a benchmark
$(BUILD)/test_data.bin: test_data.bin
	@mkdir -p $(BUILD)
	@cp test_data.bin $(BUILD)/test_data.bin

# ── Clean ─────────────────────────────────────────────────────────────────────

clean:
	rm -rf $(BUILD)
	@echo "Cleaned build/"

# ── Setup check ───────────────────────────────────────────────────────────────

setup:
	@echo "=== KWS Spike validation toolchain check ==="
	@echo ""
	@printf "%-35s" "riscv32-unknown-elf-gcc ..."
	@$(CC) --version 2>/dev/null | head -1 || echo "NOT FOUND (see README.md)"
	@printf "%-35s" "spike ..."
	@$(SPIKE) --version 2>/dev/null | head -1 || echo "NOT FOUND (see README.md)"
	@printf "%-35s" "pk (proxy kernel) ..."
	@test -f $(PK) && echo "found: $(PK)" || echo "NOT FOUND (see README.md)"
	@printf "%-35s" "python3 ..."
	@python3 --version 2>/dev/null || echo "NOT FOUND"
	@echo ""
	@printf "%-35s" "NNoM submodule (nnom/inc/nnom.h) ..."
	@test -f nnom/inc/nnom.h && echo "OK" || \
	    echo "NOT FOUND — run: git submodule update --init --recursive"
	@echo ""

# ── Help ──────────────────────────────────────────────────────────────────────

help:
	@echo "KWS Spike Validation Makefile"
	@echo ""
	@echo "Targets:"
	@echo "  all                          Build all model binaries"
	@echo "  build_strided_s16_nodil      Compile strided_s16_nodil ELF"
	@echo "  run_strided_s16_nodil        Run strided_s16_nodil on Spike"
	@echo "  test_data                    Generate test_data.bin from GSCD"
	@echo "  setup                        Check toolchain prerequisites"
	@echo "  clean                        Remove build/ directory"
	@echo ""
	@echo "See README.md for full documentation."
