/**
 * mel_compact_4blk_ch36_main.c
 *
 * Model:    mel_compact_4blk_ch36 (seed 789)
 * Accuracy: 88.7% NNoM int8 (validated on Spike, 1000 samples)
 * Params:   15,851  (15.0 KB weights)
 * Flash:    28.7 KB total (weights + NNoM firmware)
 * Classes:  11  (down go left no off on right stop up yes unknown)
 *
 * PURPOSE
 * -------
 * Validates that the model weights produce correct output on the Spike
 * RISC-V simulator before migrating to the real SoC.
 *
 * Frontend: Conv2D(1×65, stride=16, 16 filters) initialised as mel bandpass
 * filters and trained end-to-end — operates on raw Q7 audio, not MFCC.
 *
 * INPUT FILE:  test_data.bin  (generated by generate_test_data.py)
 *   Format: int32 n_real_samples, then batches of [labels[128] + audio[128×8000]]
 * OUTPUT:      stdout — one RESULT line per sample, then ACCURACY summary
 *
 * HOW TO BUILD AND RUN
 * --------------------
 * See the top-level Makefile:
 *   make build_mel_compact_4blk_ch36   — compile RISC-V ELF
 *   make run_mel_compact_4blk_ch36     — run on Spike
 *
 * WHAT TO CHECK
 * -------------
 * Expected NNoM int8 accuracy: ~88.7% on the GSCD test split.
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "mel_compact_4blk_ch36_weights.h"

#ifdef NNOM_USING_STATIC_MEMORY
static uint8_t nnom_static_buf[64 * 1024];   /* model_stat reports ~48 KB actual use */
#endif

#define NUM_CLASSES       11
#define SAMPLES_PER_CLIP  8000
#define LABEL_BATCH       128


int main(void)
{
    FILE   *fp;
    int8_t *buf;
    size_t  sz, seek;
    int     correct = 0, total = 0, n_real_samples = 0;

    fp = fopen("test_data.bin", "rb");
    if (!fp) {
        printf("ERROR: cannot open test_data.bin\n");
        printf("  Run: python3 generate_test_data.py\n");
        return 1;
    }

    fseek(fp, 0, SEEK_END);
    sz = (size_t)ftell(fp);
    fseek(fp, 0, SEEK_SET);

    buf = (int8_t *)malloc(sz);
    if (!buf) {
        printf("ERROR: malloc failed (%lu bytes)\n", (unsigned long)sz);
        fclose(fp);
        return 1;
    }

    fread(buf, 1, sz, fp);
    fclose(fp);

    {
        int32_t n;
        memcpy(&n, buf, sizeof(int32_t));
        n_real_samples = (int)n;
    }
    seek = sizeof(int32_t);

    printf("Samples: %d\n", n_real_samples);

#ifdef NNOM_USING_STATIC_MEMORY
    nnom_set_static_buf(nnom_static_buf, sizeof(nnom_static_buf));
#endif

    nnom_model_t *model = nnom_model_create();
    if (!model) {
        printf("ERROR: nnom_model_create() failed\n");
        free(buf);
        return 1;
    }

    model_stat(model);

    printf("RESULTS_START\n");

    while (seek < sz) {
        uint8_t labels[LABEL_BATCH];
        int     i;

        if (seek + (size_t)LABEL_BATCH > sz) break;
        memcpy(labels, buf + seek, (size_t)LABEL_BATCH);
        seek += (size_t)LABEL_BATCH;

        for (i = 0; i < LABEL_BATCH; i++) {
            int    pred, j;
            int8_t max_score;

            if (total >= n_real_samples) goto done;
            if (seek + (size_t)SAMPLES_PER_CLIP > sz) goto done;

            memcpy(nnom_input_data, buf + seek, (size_t)SAMPLES_PER_CLIP);
            seek += (size_t)SAMPLES_PER_CLIP;

            model_run(model);

            pred      = 0;
            max_score = nnom_output_data[0];
            for (j = 1; j < NUM_CLASSES; j++) {
                if (nnom_output_data[j] > max_score) {
                    max_score = nnom_output_data[j];
                    pred      = j;
                }
            }

            if (pred == (int)labels[i]) correct++;
            total++;

            printf("RESULT:%d,%d\n", (int)labels[i], pred);
        }
    }

done:
    printf("RESULTS_END\n");
    printf("ACCURACY:%.6f\n", total > 0 ? (double)correct / (double)total : 0.0);
    printf("TOTAL:%d\n",   total);
    printf("CORRECT:%d\n", correct);

    model_delete(model);
    free(buf);
    return 0;
}
