// spike_i2s.cpp — Spike MMIO plugin for KWS-SoC I2S receiver (apb_i2s_receiver)
//
// Simulates the I2S peripheral at base address 0x40008000.
// Register layout matches apb_i2s_receiver / i2s_regs.h from KWS-SoC:
//   0x00  ID     — peripheral ID (read-only, returns 0xDEADCAFE)
//   0x04  CONF   — config: bits[31:8] = clock divisor, bit[4] = IRQ enable
//   0x08  FIFO   — audio data: each read returns one 32-bit sample
//
// Audio data format (INMP441 MEMS mic, same as real hardware):
//   24-bit signed audio, left-aligned in a 32-bit word: sample << 8 in the mic,
//   which the firmware undoes with: int8_t q7 = (int8_t)(raw >> 16)
//
// Input file: raw binary of int8 Q7 audio samples (one byte per sample, 8000
// samples per second at 8 kHz). Generated by scripts/gen_spike_audio.py.
// The plugin converts int8 Q7 → 32-bit I2S format: sample << 16.
//
// Interrupt delivery:
//   - On CONF write with IRQ_EN=1: immediately asserts PLIC IRQ I2S_IRQ_ID
//   - After firmware reads I2S_FIFO_DEPTH (8) samples from FIFO: deasserts
//     then reasserts IRQ to trigger the next batch (simulates FIFO refill)
//   - When all audio data is consumed: IRQ is deasserted permanently
//
// PLIC IRQ ID: I2S_IRQ_ID = 2 (must match firmware and PLIC configuration)

#include <riscv/devices.h>
#include <riscv/abstract_device.h>
#include <riscv/sim.h>
#include <cstdio>
#include <cstring>
#include <vector>
#include <string>

/* I2S_FIFO_DEPTH: must match the firmware's I2S_FIFO_DEPTH.
 * Default = 8 (real SoC hardware FIFO depth).
 * For Spike simulation, recompile with -DI2S_FIFO_DEPTH=8000 to reduce
 * PLIC overhead from 1000 ISRs to 1 ISR. */
#ifndef I2S_FIFO_DEPTH
#define I2S_FIFO_DEPTH  8
#endif
#define I2S_IRQ_ID      2

class spike_i2s_t : public abstract_device_t {
public:
    spike_i2s_t(const sim_t* sim, const std::string& audio_file) : sim_(sim) {
        FILE* f = fopen(audio_file.c_str(), "rb");
        if (f) {
            fseek(f, 0, SEEK_END);
            long sz = ftell(f);
            fseek(f, 0, SEEK_SET);
            audio_data_.resize(sz);
            fread(audio_data_.data(), 1, sz, f);
            fclose(f);
            fprintf(stderr, "[I2S] Loaded %ld samples from %s\n",
                    sz, audio_file.c_str());
        } else {
            fprintf(stderr, "[I2S] WARNING: cannot open audio file: %s\n",
                    audio_file.c_str());
        }
    }

    bool load(reg_t addr, size_t len, uint8_t* bytes) override {
        uint32_t val = 0;
        switch (addr) {
            case 0x00:  // ID register — 0xDEADCAFE per apb_i2s_receiver.v
                val = 0xDEADCAFEu;
                break;

            case 0x04:  // CONF register
                val = conf_;
                break;

            case 0x08:  // FIFO register — returns next audio sample
                if (read_pos_ < audio_data_.size()) {
                    // Convert int8 Q7 to 24-bit left-aligned in 32-bit word.
                    // Firmware ISR does: q7 = (int8_t)(raw >> 16) to undo this.
                    int8_t q7 = (int8_t)audio_data_[read_pos_++];
                    val = (uint32_t)((int32_t)q7 << 16);
                } else {
                    val = 0;  // silence when data exhausted
                    exhausted_ = true;
                }

                fifo_reads_++;
                if (fifo_reads_ >= I2S_FIFO_DEPTH) {
                    fifo_reads_ = 0;
                    // All 8 samples read — trigger next batch interrupt
                    auto intctrl = sim_->get_intctrl();
                    if (intctrl) {
                        intctrl->set_interrupt_level(I2S_IRQ_ID, 0);  // deassert
                        if (!exhausted_) {
                            intctrl->set_interrupt_level(I2S_IRQ_ID, 1);  // reassert
                        }
                    }
                }
                break;

            default:
                val = 0;
                break;
        }
        memcpy(bytes, &val, len < 4 ? len : 4);
        return true;
    }

    bool store(reg_t addr, size_t len, const uint8_t* bytes) override {
        uint32_t val = 0;
        memcpy(&val, bytes, len < 4 ? len : 4);

        switch (addr) {
            case 0x04: {  // CONF register — per i2s_regs.h:
                //   CONF_DIV    bits[31:8]  (mask 0xFFFFFF00)
                //   CONF_IRQ_EN bit[4]      (mask 0x10)
                uint32_t old_conf = conf_;
                conf_ = val;
                uint32_t clk_div = (val >> 8) & 0xFFFFFFu;
                uint8_t irq_en = (val >> 4) & 1u;

                fprintf(stderr, "[I2S] Configured: clk_div=%u irq_en=%u\n",
                        clk_div, irq_en);

                // Assert first interrupt if IRQ just enabled and we have data
                if (irq_en && !((old_conf >> 4) & 1u) && !exhausted_) {
                    auto intctrl = sim_->get_intctrl();
                    if (intctrl) {
                        intctrl->set_interrupt_level(I2S_IRQ_ID, 1);
                    }
                }
                break;
            }
            default:
                break;
        }
        return true;
    }

    reg_t size() override { return 0x100; }

private:
    const sim_t* sim_;
    std::vector<uint8_t> audio_data_;
    size_t read_pos_ = 0;
    uint32_t conf_ = 0;
    int fifo_reads_ = 0;
    bool exhausted_ = false;
};

static spike_i2s_t* spike_i2s_parse(const void* fdt, const sim_t* sim,
                                      reg_t* base,
                                      const std::vector<std::string>& sargs) {
    *base = 0x40008000;
    std::string audio_file = sargs.size() > 0 ? sargs[0] : "audio.bin";
    return new spike_i2s_t(sim, audio_file);
}

static std::string spike_i2s_generate(const sim_t* sim,
                                       const std::vector<std::string>& sargs) {
    return "";  // no DTS entry needed
}

REGISTER_DEVICE(spike_i2s, spike_i2s_parse, spike_i2s_generate)
