#!/usr/bin/env python3
"""
gen_spike_audio.py — Generate raw int8 Q7 audio files for the Spike I2S plugin.

Reads WAV files from the GSCD dataset and converts them to the format expected
by spike_i2s.cpp: raw binary, one int8 Q7 byte per sample, 8000 samples per
second (8 kHz, mono).

The Q7 format matches what the firmware ISR produces from the I2S FIFO:
    q7 = (int8_t)(raw >> 16)  — signed 8-bit, dec_bits=7, range [-128..127]
    corresponds to float audio in [-1.0, 1.0] * 128

Usage
-----
# Single clip from a WAV file:
python3 scripts/gen_spike_audio.py \\
    --wav /path/to/yes/abc123.wav \\
    --output test_clips/yes_abc123.bin

# All test clips from GSCD (writes one .bin per clip, labelled by class):
python3 scripts/gen_spike_audio.py \\
    --all \\
    --dataset /workspace/Desktop/Models/data/dataset \\
    --output-dir test_clips/ \\
    --max-per-class 20       # optional limit for quick testing

# Generate test_data.bin clips from pre-existing test_data.bin (fastest):
python3 scripts/gen_spike_audio.py \\
    --from-test-data build/test_data.bin \\
    --output-dir test_clips/ \\
    --max-per-class 20

Output format
-------------
Each .bin file: 8000 bytes, raw int8 Q7 audio (1 second at 8 kHz).
Filename convention: <class_name>_<index>.bin  e.g. yes_0042.bin
"""

import argparse
import os
import sys
import struct
import numpy as np

CLASSES = ['down', 'go', 'left', 'no', 'off', 'on',
           'right', 'stop', 'up', 'yes', 'unknown']
TARGET_SR = 8000
SAMPLES_PER_CLIP = 8000  # 1 second at 8 kHz


def wav_to_q7(wav_path: str) -> np.ndarray:
    """Load a WAV file and convert to int8 Q7 at 8 kHz."""
    try:
        import scipy.io.wavfile as wavfile
        sr, data = wavfile.read(wav_path)
    except ImportError:
        import wave, array
        with wave.open(wav_path, 'rb') as wf:
            sr = wf.getframerate()
            n = wf.getnframes()
            raw = wf.readframes(n)
            data = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0

    # Convert to float32 in [-1, 1]
    if data.dtype == np.int16:
        data = data.astype(np.float32) / 32768.0
    elif data.dtype == np.int32:
        data = data.astype(np.float32) / 2147483648.0
    elif data.dtype == np.float32 or data.dtype == np.float64:
        data = data.astype(np.float32)
    else:
        data = data.astype(np.float32)

    # Stereo → mono
    if data.ndim == 2:
        data = data.mean(axis=1)

    # Resample from native SR to 8 kHz
    if sr != TARGET_SR:
        from fractions import Fraction
        ratio = Fraction(TARGET_SR, sr).limit_denominator(100)
        # Simple polyphase resampling via scipy if available, else basic skip
        try:
            from scipy.signal import resample_poly
            data = resample_poly(data, ratio.numerator, ratio.denominator)
        except ImportError:
            # Fallback: simple decimation (only works for integer ratios)
            step = sr // TARGET_SR
            data = data[::step]

    # Pad or truncate to exactly SAMPLES_PER_CLIP
    if len(data) < SAMPLES_PER_CLIP:
        data = np.pad(data, (0, SAMPLES_PER_CLIP - len(data)))
    else:
        data = data[:SAMPLES_PER_CLIP]

    # Normalize to [-1, 1]
    peak = np.max(np.abs(data))
    if peak > 1e-6:
        data = data / peak

    # Convert to int8 Q7: clip(round(x * 128), -128, 127)
    q7 = np.clip(np.round(data * 128.0), -128, 127).astype(np.int8)
    return q7


def from_test_data(test_data_path: str, output_dir: str, max_per_class: int):
    """Extract clips from test_data.bin (generated by generate_test_data.py)."""
    os.makedirs(output_dir, exist_ok=True)

    with open(test_data_path, 'rb') as f:
        data = f.read()

    # Header: int32 n_real_samples
    n_real = struct.unpack_from('<i', data, 0)[0]
    offset = 4
    total = 0
    counts = [0] * len(CLASSES)
    skipped = 0

    while offset < len(data) and total < n_real:
        # Read batch: 128 labels + 128 * 8000 audio bytes
        batch_size = 128
        if offset + batch_size > len(data):
            break
        labels = list(data[offset:offset + batch_size])
        offset += batch_size

        for i in range(batch_size):
            if total >= n_real:
                break
            if offset + SAMPLES_PER_CLIP > len(data):
                break

            label = labels[i]
            audio = np.frombuffer(data[offset:offset + SAMPLES_PER_CLIP],
                                  dtype=np.int8).copy()
            offset += SAMPLES_PER_CLIP
            total += 1

            if max_per_class > 0 and counts[label] >= max_per_class:
                skipped += 1
                continue

            class_name = CLASSES[label] if label < len(CLASSES) else 'unknown'
            fname = f"{class_name}_{counts[label]:04d}.bin"
            out_path = os.path.join(output_dir, fname)
            audio.tofile(out_path)
            counts[label] += 1

    total_written = sum(counts)
    print(f"Extracted {total_written} clips to {output_dir}/ (skipped {skipped})")
    for i, cls in enumerate(CLASSES):
        print(f"  {cls:>10s}: {counts[i]}")


def from_wav(wav_path: str, output_path: str):
    """Convert a single WAV file to Q7 binary."""
    q7 = wav_to_q7(wav_path)
    q7.tofile(output_path)
    print(f"Wrote {len(q7)} samples to {output_path}")


def from_dataset(dataset_path: str, output_dir: str, max_per_class: int):
    """Generate clips from GSCD test split."""
    os.makedirs(output_dir, exist_ok=True)

    test_list_path = os.path.join(dataset_path, 'testing_list.txt')
    if not os.path.exists(test_list_path):
        print(f"ERROR: {test_list_path} not found", file=sys.stderr)
        sys.exit(1)

    with open(test_list_path) as f:
        test_files = [l.strip() for l in f if l.strip()]

    counts = [0] * len(CLASSES)
    written = 0

    for rel_path in test_files:
        parts = rel_path.split('/')
        if len(parts) < 2:
            continue
        class_name = parts[0]
        if class_name not in CLASSES[:10]:
            class_name = 'unknown'
        label = CLASSES.index(class_name)

        if max_per_class > 0 and counts[label] >= max_per_class:
            continue

        wav_path = os.path.join(dataset_path, rel_path)
        if not os.path.exists(wav_path):
            continue

        try:
            q7 = wav_to_q7(wav_path)
            fname = f"{class_name}_{counts[label]:04d}.bin"
            q7.tofile(os.path.join(output_dir, fname))
            counts[label] += 1
            written += 1
        except Exception as e:
            print(f"WARNING: skip {wav_path}: {e}", file=sys.stderr)

    print(f"Wrote {written} clips to {output_dir}/")
    for i, cls in enumerate(CLASSES):
        if counts[i]:
            print(f"  {cls:>10s}: {counts[i]}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate raw int8 Q7 audio clips for Spike I2S plugin')
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--wav', help='Single WAV file to convert')
    group.add_argument('--from-test-data',
                       help='Extract clips from existing test_data.bin')
    group.add_argument('--all', action='store_true',
                       help='Generate all clips from GSCD test split')

    parser.add_argument('--output', help='Output .bin path (for --wav)')
    parser.add_argument('--output-dir', default='test_clips',
                        help='Output directory (for --all / --from-test-data)')
    parser.add_argument('--dataset',
                        default='/workspace/Desktop/Models/data/dataset',
                        help='GSCD dataset root path')
    parser.add_argument('--max-per-class', type=int, default=0,
                        help='Limit clips per class (0 = no limit)')
    args = parser.parse_args()

    if args.wav:
        if not args.output:
            parser.error('--wav requires --output')
        from_wav(args.wav, args.output)
    elif args.from_test_data:
        from_test_data(args.from_test_data, args.output_dir, args.max_per_class)
    elif args.all:
        from_dataset(args.dataset, args.output_dir, args.max_per_class)


if __name__ == '__main__':
    main()
